version: '3.8'

services:
  bybit-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: bybit-mcp:latest
    container_name: bybit-mcp
    restart: unless-stopped
    ports:
      - "50051:50051"
    volumes:
      - ./config.json:/app/config.json:ro
    environment:
      - TZ=Asia/Shanghai
      - BYBIT_API_KEY=您的API密钥
      - BYBIT_API_SECRET=您的API密钥
      - BYBIT_BASE_URL=https://api.bybit.com
      - BYBIT_DEBUG=false
      - SERVER_PORT=50051
      - LOGGER_LEVEL=info
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "50051"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - bybit-network

networks:
  bybit-network:
    driver: bridge